/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function vaultsaccount_timestamp(a: number, b: number, c: number): void;
export function vaultsaccount_get_price(a: number, b: number, c: number): void;
export function vaultsaccount_get_confidence(a: number, b: number, c: number): void;
export function vaultsaccount_get_price_quote(a: number, b: number, c: number): void;
export function vaultsaccount_get_confidence_quote(a: number, b: number, c: number): void;
export function vaultsaccount_update_oracle(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function vaultsaccount_update_quote_oracle(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbg_stateaccount_free(a: number): void;
export function stateaccount_load(a: number): number;
export function stateaccount_get_bump(a: number): number;
export function stateaccount_get_vaults_account(a: number, b: number): void;
export function __wbg_statementaccount_free(a: number): void;
export function __wbg_borrowpositioninfo_free(a: number): void;
export function __wbg_get_borrowpositioninfo_vault_id(a: number): number;
export function __wbg_set_borrowpositioninfo_vault_id(a: number, b: number): void;
export function __wbg_get_borrowpositioninfo_borrowed_quantity(a: number): number;
export function __wbg_set_borrowpositioninfo_borrowed_quantity(a: number, b: number): void;
export function __wbg_get_borrowpositioninfo_owed_quantity(a: number): number;
export function __wbg_set_borrowpositioninfo_owed_quantity(a: number, b: number): void;
export function __wbg_lppositioninfo_free(a: number): void;
export function __wbg_get_lppositioninfo_vault_id(a: number): number;
export function __wbg_set_lppositioninfo_vault_id(a: number, b: number): void;
export function __wbg_get_lppositioninfo_strategy_id(a: number): number;
export function __wbg_set_lppositioninfo_strategy_id(a: number, b: number): void;
export function __wbg_get_lppositioninfo_deposited_quote_quantity(a: number): number;
export function __wbg_set_lppositioninfo_deposited_quote_quantity(a: number, b: number): void;
export function __wbg_get_lppositioninfo_earned_base_quantity(a: number): number;
export function __wbg_set_lppositioninfo_earned_base_quantity(a: number, b: number): void;
export function __wbg_get_lppositioninfo_earned_quote_quantity(a: number): number;
export function __wbg_set_lppositioninfo_earned_quote_quantity(a: number, b: number): void;
export function vaultsaccount_max_borrow_for(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_get_borrow_position_info(a: number, b: number, c: number, d: number, e: number): void;
export function vaultsaccount_get_lp_position_info(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function statementaccount_load(a: number): number;
export function statementaccount_reload(a: number, b: number): void;
export function statementaccount_buffer(a: number): number;
export function statementaccount_get_bump(a: number): number;
export function statementaccount_vaults_to_refresh(a: number, b: number): void;
export function statementaccount_refresh(a: number, b: number, c: number): void;
export function statementaccount_positions_len(a: number): number;
export function statementaccount_owner(a: number, b: number): void;
export function statementaccount_remaining_permitted_debt(a: number): number;
export function __wbg_strategyinfo_free(a: number): void;
export function __wbg_get_strategyinfo_has_lend(a: number): number;
export function __wbg_set_strategyinfo_has_lend(a: number, b: number): void;
export function __wbg_get_strategyinfo_has_swap(a: number): number;
export function __wbg_set_strategyinfo_has_swap(a: number, b: number): void;
export function __wbg_get_strategyinfo_has_trade(a: number): number;
export function __wbg_set_strategyinfo_has_trade(a: number, b: number): void;
export function __wbg_get_strategyinfo_utilization_quote(a: number): number;
export function __wbg_set_strategyinfo_utilization_quote(a: number, b: number): void;
export function vaultsaccount_strategy_info(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_count_strategies(a: number, b: number, c: number): void;
export function vaultsaccount_does_lend(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_does_swap(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_balance_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_balance_quote(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_lock_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_lock_quote(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_utilization_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_utilization_quote(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_swap(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function vaultsaccount_liquidity(a: number, b: number, c: number, d: number): void;
export function __wbg_vaultsaccount_free(a: number): void;
export function __wbg_vaultskeyswithid_free(a: number): void;
export function __wbg_get_vaultskeyswithid_base_key(a: number): number;
export function __wbg_set_vaultskeyswithid_base_key(a: number, b: number): void;
export function __wbg_get_vaultskeyswithid_quote_key(a: number): number;
export function __wbg_set_vaultskeyswithid_quote_key(a: number, b: number): void;
export function __wbg_get_vaultskeyswithid_index(a: number): number;
export function __wbg_set_vaultskeyswithid_index(a: number, b: number): void;
export function vaultsaccount_load(a: number): number;
export function vaultsaccount_reload(a: number, b: number): void;
export function vaultsaccount_buffer(a: number): number;
export function vaultsaccount_vaults_keys_with_id(a: number, b: number): void;
export function vaultsaccount_base_token(a: number, b: number, c: number): void;
export function vaultsaccount_quote_token(a: number, b: number, c: number): void;
export function vaultsaccount_base_reserve(a: number, b: number, c: number): void;
export function vaultsaccount_quote_reserve(a: number, b: number, c: number): void;
export function vaultsaccount_oracle_base(a: number, b: number, c: number): void;
export function vaultsaccount_oracle_quote(a: number, b: number, c: number): void;
export function vaultsaccount_base_oracle_enabled(a: number, b: number, c: number): void;
export function vaultsaccount_quote_oracle_enabled(a: number, b: number, c: number): void;
export function vaultsaccount_has_lending(a: number, b: number, c: number): void;
export function vaultsaccount_has_swap(a: number, b: number, c: number): void;
export function vaultsaccount_refresh(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_lending_apy(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_deposit(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function price_denominator(): number;
export function fraction_denominator(): number;
export function vaultsaccount_size(): number;
export function __wbg_set_lppositioninfo_deposited_base_quantity(a: number, b: number): void;
export function __wbg_set_lppositioninfo_position_value(a: number, b: number): void;
export function __wbg_get_lppositioninfo_position_value(a: number): number;
export function __wbg_set_strategyinfo_utilization_base(a: number, b: number): void;
export function __wbg_set_strategyinfo_locked_quote(a: number, b: number): void;
export function __wbg_set_strategyinfo_locked_base(a: number, b: number): void;
export function __wbg_set_strategyinfo_balance_quote(a: number, b: number): void;
export function __wbg_set_strategyinfo_balance_base(a: number, b: number): void;
export function __wbg_get_strategyinfo_balance_base(a: number): number;
export function __wbg_get_strategyinfo_balance_quote(a: number): number;
export function __wbg_get_strategyinfo_utilization_base(a: number): number;
export function __wbg_get_strategyinfo_locked_quote(a: number): number;
export function __wbg_get_strategyinfo_locked_base(a: number): number;
export function __wbg_get_lppositioninfo_deposited_base_quantity(a: number): number;
export function vaultsaccount_vaults_len(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
