/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function ret_error(a: number): void;
export function __wbg_stateaccount_free(a: number): void;
export function stateaccount_load(a: number): number;
export function stateaccount_get_bump(a: number): number;
export function stateaccount_get_vaults_account(a: number, b: number): void;
export function vaultsaccount_get_price(a: number, b: number, c: number): void;
export function vaultsaccount_get_confidence(a: number, b: number, c: number): void;
export function vaultsaccount_get_price_quote(a: number, b: number, c: number): void;
export function vaultsaccount_get_confidence_quote(a: number, b: number, c: number): void;
export function vaultsaccount_update_oracle(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function vaultsaccount_update_quote_oracle(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function price_denominator(): number;
export function fraction_denominator(): number;
export function __wbg_strategyinfo_free(a: number): void;
export function __wbg_get_strategyinfo_has_lend(a: number): number;
export function __wbg_set_strategyinfo_has_lend(a: number, b: number): void;
export function __wbg_get_strategyinfo_has_swap(a: number): number;
export function __wbg_set_strategyinfo_has_swap(a: number, b: number): void;
export function __wbg_get_strategyinfo_has_trade(a: number): number;
export function __wbg_set_strategyinfo_has_trade(a: number, b: number): void;
export function __wbg_get_strategyinfo_balance_base(a: number): number;
export function __wbg_set_strategyinfo_balance_base(a: number, b: number): void;
export function __wbg_get_strategyinfo_balance_quote(a: number): number;
export function __wbg_set_strategyinfo_balance_quote(a: number, b: number): void;
export function __wbg_get_strategyinfo_locked_base(a: number): number;
export function __wbg_set_strategyinfo_locked_base(a: number, b: number): void;
export function __wbg_get_strategyinfo_locked_quote(a: number): number;
export function __wbg_set_strategyinfo_locked_quote(a: number, b: number): void;
export function __wbg_get_strategyinfo_utilization_base(a: number): number;
export function __wbg_set_strategyinfo_utilization_base(a: number, b: number): void;
export function __wbg_get_strategyinfo_utilization_quote(a: number): number;
export function __wbg_set_strategyinfo_utilization_quote(a: number, b: number): void;
export function vaultsaccount_strategy_info(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_count_strategies(a: number, b: number, c: number): void;
export function vaultsaccount_does_lend(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_does_swap(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_balance_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_balance_quote(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_lock_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_lock_quote(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_utilization_base(a: number, b: number, c: number, d: number): void;
export function vaultsaccount_utilization_quote(a: number, b: number, c: number, d: number): void;
export function __wbg_statementaccount_free(a: number): void;
export function statementaccount_load(a: number): number;
export function statementaccount_get_bump(a: number): number;
export function __wbg_vaultsaccount_free(a: number): void;
export function __wbg_basekeywithid_free(a: number): void;
export function __wbg_get_basekeywithid_key(a: number): number;
export function __wbg_set_basekeywithid_key(a: number, b: number): void;
export function __wbg_get_basekeywithid_index(a: number): number;
export function __wbg_set_basekeywithid_index(a: number, b: number): void;
export function vaultsaccount_load(a: number): number;
export function vaultsaccount_vaults_len(a: number): number;
export function vaultsaccount_size(): number;
export function vaultsaccount_base_token_with_id(a: number, b: number): void;
export function vaultsaccount_base_token(a: number, b: number, c: number): void;
export function vaultsaccount_quote_token(a: number, b: number, c: number): void;
export function vaultsaccount_base_reserve(a: number, b: number, c: number): void;
export function vaultsaccount_quote_reserve(a: number, b: number, c: number): void;
export function vaultsaccount_oracle_base(a: number, b: number, c: number): void;
export function vaultsaccount_oracle_quote(a: number, b: number, c: number): void;
export function vaultsaccount_base_oracle_enabled(a: number, b: number, c: number): void;
export function vaultsaccount_quote_oracle_enabled(a: number, b: number, c: number): void;
export function vaultsaccount_has_lending(a: number, b: number, c: number): void;
export function vaultsaccount_has_swap(a: number, b: number, c: number): void;
export function vaultsaccount_lending_apy(a: number, b: number, c: number): void;
export function vaultsaccount_swap(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function vaultsaccount_liquidity(a: number, b: number, c: number, d: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
